# Generated by Django 5.1.5 on 2025-01-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_cat', '0003_alter_lostcat_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostcat',
            name='status',
            field=models.CharField(choices=[('protected', '保護'), ('lost', '迷子')], default='lost', max_length=10),
        ),
    ]
