# Generated by Django 5.1.5 on 2025-01-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_cat', '0004_lostcat_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostcat',
            name='sex',
            field=models.CharField(choices=[('male_neutering', 'オス（去勢済）'), ('male_not_neutering', 'オス（去勢未）'), ('female_spaying', 'メス（避妊済）'), ('female_not_spaying', 'メス（避妊未）'), ('not_clear', '不明')], default='male_neutering', max_length=20),
        ),
    ]
