# Generated by Django 5.1.5 on 2025-01-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_cat', '0005_lostcat_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostcat',
            name='age_months',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lostcat',
            name='age_years',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
