# Generated by Django 5.1.5 on 2025-01-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_cat', '0006_lostcat_age_months_lostcat_age_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostcat',
            name='lost_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
