# Generated by Django 5.1.5 on 2025-01-26 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_cat', '0007_lostcat_lost_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostcat',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
