# Generated by Django 5.1.5 on 2025-01-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_cat', '0008_lostcat_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostcat',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='lostcat',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
