# Generated by Django 5.1.5 on 2025-01-30 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_cat', '0009_lostcat_photo2_lostcat_photo3'),
    ]

    operations = [
        migrations.CreateModel(
            name='SightingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation', models.TextField(max_length=255)),
                ('lostcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sighting_reports', to='lost_cat.lostcat')),
            ],
        ),
    ]
