# Generated by Django 5.1.5 on 2025-02-04 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lost_cat', '0010_sightingreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lostcat',
            old_name='description3',
            new_name='description_collar',
        ),
        migrations.RenameField(
            model_name='lostcat',
            old_name='description4',
            new_name='description_eye',
        ),
    ]
