# Generated by Django 5.1.5 on 2025-02-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_cat', '0011_rename_description3_lostcat_description_collar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostcat',
            name='ear_cut',
            field=models.CharField(choices=[('not_sakura_cat', 'なし'), ('sakura_cat_right', 'あり（右）'), ('sakura_cat_left', 'あり（左）')], default='not_sakura_cat', max_length=20),
        ),
    ]
