# Generated by Django 5.1.5 on 2025-02-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_cat', '0012_lostcat_ear_cut'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostcat',
            name='lost_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
