# Generated by Django 5.1.5 on 2025-03-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_cat', '0014_sightingreport_lost_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sightingreport',
            name='email',
            field=models.EmailField(blank=True, help_text='連絡が必要な場合に備えて、メールアドレスを任意で入力できます', max_length=254, null=True, verbose_name='メールアドレス'),
        ),
        migrations.AddField(
            model_name='sightingreport',
            name='phone_number',
            field=models.CharField(blank=True, help_text='連絡が必要な場合に備えて、電話番号を任意で入力できます', max_length=15, null=True, verbose_name='電話番号'),
        ),
    ]
