# Generated by Django 5.1.5 on 2025-03-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_cat', '0015_sightingreport_email_sightingreport_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResolvedLostCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='resolved_cats/')),
                ('resolved_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
