# Generated by Django 5.1.5 on 2025-03-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_cat', '0017_alter_resolvedlostcat_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resolvedlostcat',
            name='photo',
            field=models.ImageField(blank=True, default='resolved_cats/no-image.jpg', upload_to='resolved_cats/'),
        ),
    ]
