# Generated by Django 5.1.5 on 2025-04-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_cat', '0018_alter_resolvedlostcat_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostcat',
            name='description1',
            field=models.TextField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='lostcat',
            name='description2',
            field=models.TextField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='lostcat',
            name='description_collar',
            field=models.TextField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='lostcat',
            name='description_eye',
            field=models.TextField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='lostcat',
            name='lost_location',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='lostcat',
            name='name',
            field=models.CharField(max_length=8),
        ),
    ]
