# Generated by Django 5.1.5 on 2025-03-15 07:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='ユーザー名は英数字のみ使用できます。', regex='^[a-zA-Z0-9]+$')], verbose_name='ユーザー名'),
        ),
    ]
