# Generated by Django 5.1.5 on 2025-03-15 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_nickname_alter_account_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='nickname',
        ),
    ]
